server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:23306}/mutantesdb?useSSL=true&serverTimezone=America/Bogota
    username: root
    password: mercadolibre.2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
      initial-size: 5
      max-active: 10
      max-idle: 15
      max-wait: 20000
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect